# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

val1 = 0
val2 = 1
val3 = 0
sum = 0

for i in range(32):
    val3 = val1 + val2
    val1 = val2
    val2 = val3
    if val3 <= 4000000 and val3%2 == 0:
        sum += val3
print(sum)
