# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

wert1 = 0
wert2 = 1
wert3 = 0
sum = 0

for i in range(32):
    wert3 = wert1 + wert2
    wert1 = wert2
    wert2 = wert3
    if wert3 <= 4000000 and wert3%2 == 0:
        sum += wert3
print(sum)
